### ISSUE TITLE
value not passed to TextInput

### ISSUE THREAD

**Issue by gurucomkz** [WrathChaos/react-native-improved-text-input#2]
Hi.
Cannot set an initial value to the component.
Figured out that `...rest` in `ImprovedTextInput.js` does not contain `value` property.

Works if change 
```jsx
<TextInput {...rest} style={!value ? [style, placeholderStyle] : style} />
```
to 
```jsx
<TextInput {...rest} value={value} style={!value ? [style, placeholderStyle] : style} />
```

"react": "16.9.0"
"react-native": "0.61.5"
"react-native-improved-text-input": "0.0.1"

**Comment by kuraydev** [comment]
Hello @gurucomkz 

I am so sorry, I totally forgot this library 🤦‍♂️

I converted it to typescript and made it a bit better :) It should solve the value problem.

Thank you for reporting tho

**Comment by TelfyC** [comment]
Hi. 
I found the same problem in Version 1.5.0
I check the code in ImprovedTextInput.js and there is still no init value

**Comment by kuraydev** [comment]
Hello @TelfyC 
Why do you need an init value for that?
